Exercise with Python\
Email: rdp135@chem.rutgers.edu

Agenda:

    * Q & A
    If no Q & A:
        * Review of 10 Question Problem Set from Session 1
        * Code submissions for problems below (share screens)

1. Write a method which takes a string as an argument and returns the number of characters in the string.

In [1]:
def count_string(str_):
    return len(str_)

print(count_string('trung'))

5


2. Write a method which takes in multiple string arguments and returns a dictionary to access them by increasing integers starting from 0.

In [3]:
def str_to_dict(*strings):
    d_ = {}
    for n, i in enumerate(strings):
        d_.update({n : i})
    return d_

dictionary = str_to_dict('Hadi', 'Trung', 'Alexei', 'Delia')
print(dictionary)

{0: 'Hadi', 1: 'Trung', 2: 'Alexei', 3: 'Delia'}


3. Generate a list of numbers from 0 - 5.2 in steps of .2 using list comprehension.

In [7]:
import numpy as np

print([round(i, 3) for i in np.arange(0,5.2,0.2)])

[0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0]


4. Generate a list, containing a type of your choice, which implements a double for loop.

In [11]:
numbers = []
for i in range(11):
    for j in range(10):
        numbers.append((i, j))
print(numbers)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9)]


In [20]:
def search(n):
    for num in numbers:
        if (10, 8) == n:
            print(n)
            break
            
search((10, 8))

(10, 8)


5. Rewrite the method from 2. so that it contains a while loop.

Skipped.

6. Generate a series of numbers and show a histogram of the data.

Already done.

7. Add a mechanism to check if all strings are unique and only generate a dictionary with the unique strings for the method in 2.

In [34]:
strings = ['Robert', 'Alexei', 'Hadi', 'Trung']

def check_unique(str_lst):
    s_ = set(str_lst)
    sl = [i for i in s_]
    if len(sl) == len(str_lst):
        print('Unique!')
    else:
        print('Not Unique!')

check_unique(strings)

Unique!


8. Write a function that generates a numpy 2D array of floats and prints the maximum value it contains.

In [47]:
import random
def max2d():
    H = np.asarray([[random.uniform(2, 100) for i in range(3)] for j in range(5)])
    print(H)
    max_ = H[H == H.max()][0]
    print(max_)

max2d()

[[42.58309173 44.86967067 26.40537333]
 [22.67633445 25.62762816 52.16544932]
 [13.69776253 60.16225445 80.68861221]
 [43.39410349 23.56657589 17.34488882]
 [63.29955311 88.15143232 56.13694986]]
88.15143232174417


In [54]:
def max2d():
    H = np.arange(0, 20, .1).reshape(40, 5)
    for i in range(H.shape[1]):
        max_ = H[i, :].max()
        print(max_)

max2d()

0.4
0.9
1.4000000000000001
1.9000000000000001
2.4000000000000004


9. Write an algorithm for guessing a given password using brute force.

Try it on your own.

10. Write the key and value from 2. as separate columns in a text file. After writing, read the text file and print its contents.

Try it on your own.